project:
  type: website

website:
  title: "Knight Light"
  favicon: chessIcon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: fpga.qmd
        text: FPGA Design
      - href: mcu.qmd
        text: MCU Design
      - href: results.qmd
        text: Results
      - href: documentation.qmd
        text: Documentation
      - href: about.qmd
        text: The Team

format:
  html:
    theme: vapor
    css: styles.css
    toc: true



